# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8f4f1c6a1d9edfeb182ed40e7322ed356146fde2935713780bf20e019642085fd67f09fb7c0564a19f49306f669193027a0c059ad41dc6365fb74dc01ef3074

test:
  secret_key_base: 7b1cb533da09dd0ce49fec337d79969e020c56fd49bc884f72516767af13524fde8d2464fcf967917ba574911e391fe2d744e1982a69eaeafeb6ab576e31c545

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
